services:
  - type: web
    name: project-kisinia-backend
    env: python
    plan: free
    rootDir: project_kisinia
    buildCommand: "pip install -r requirement.txt"
    startCommand: "python manage.py migrate && gunicorn kisinia_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_gtrC25MfARql@ep-billowing-truth-aiw66al5-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      - key: ALLOWED_HOSTS
        value: project-kisinia-backend.onrender.com
      - key: MEDIA_ROOT
        value: /opt/render/project/src/media
